# Generated by Django 4.0.3 on 2022-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('genre', models.CharField(max_length=100)),
                ('read', models.CharField(max_length=100)),
                ('libs', models.CharField(max_length=100)),
            ],
        ),
    ]
