# Generated by Django 4.0.3 on 2022-05-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_library_book_libs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='address',
        ),
    ]
