# Generated by Django 4.0.3 on 2022-05-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_lib_remove_book_libs_delete_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='libs',
            field=models.ManyToManyField(to='main_app.lib'),
        ),
    ]
